sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 111111

  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: ${OSS_ACCESS_KEY_ID}
    access-key-secret: ${OSS_ACCESS_KEY_SECRET}
    bucket-name: hanjiaqi
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 1
  wechat:
    app-id: wx6a65eee085012368
    app-secret: d8f6b2db5837f65d63b9025c042384a0